### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MatteoCappe** [MatteoCappe/Matteo_thesis_workbook#2]
Tasks:

- [ ] Research on EROS and SCARF
- [ ] Research on graph-based and attention-based Networks
- [ ] Research on PnP
- [ ] See how the simulator works and analyze the synthetic dataset
- [ ] Try out OnePose and Dope codes
- [ ] Correct the pipeline if needed

List of useful papers:
(will update next week)

- [ ]
